services:
  load-automated-data:
    image: curlimages/curl
    depends_on:
      api:
        condition: service_healthy
    entrypoint: sh
    command:
      - -c
      - |
        curl -X POST -H 'content-type: application/json' http://api:3000/preprints -d'@/data/automation/85111/v1/payload.json'
        curl -X POST -H 'content-type: application/json' http://api:3000/preprints -d'@/data/automation/85111/v2/payload.json'
    volumes:
      - ./data:/data

  image-server:
    environment:
      - SOURCE_STATIC=S3Source
      - S3SOURCE_ENDPOINT=http://minio:9000/
      - S3SOURCE_ACCESS_KEY_ID=minio
      - S3SOURCE_SECRET_KEY=miniotest
      - S3SOURCE_BASICLOOKUPSTRATEGY_PATH_PREFIX=automation/
      - S3SOURCE_BASICLOOKUPSTRATEGY_BUCKET_NAME=eppdata

  app:
    depends_on:
      load-automated-data:
        condition: service_completed_successfully
    environment:
      IS_AUTOMATED: yeah

  # Create bucket and upload data
  createbucket:
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minio miniotest;
      /usr/bin/mc mb myminio/eppdata || true;
      /usr/bin/mc mirror /automationdata myminio/eppdata/automation;
      # Set to public to host local PDFs
      /usr/bin/mc anonymous set public myminio/eppdata;
      exit 0;
      "
    volumes:
      - ./data/automation:/automationdata
