version: '3.4'
services:
  # Main app server
  app:
    build:
      context: .
      target: dev
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'apk add curl; curl -X POST http://app:3000/'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2s
    environment:
      API_SERVER: http://api:3000
      MANUSCRIPT_CONFIG_FILE: ./test-utils/data/manuscripts.json
    ports:
    - 3001:3000
    volumes:
    - ./:/opt/epp-client/
    - node_modules:/opt/epp-client/node_modules

  # expose API and client via proxy
  api:
    image: nginx:latest
    ports:
    - 3000:3000
    volumes:
    - ./.docker/nginx-browser-test.conf:/etc/nginx/conf.d/default.conf
    - ./test-utils/data/:/www/test-data/

volumes:
  data:
  node_modules:
