version: '3.4'
services:
  # Main app server
  app:
    build:
      context: .
      target: dev
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'apk add curl; curl -X POST http://app:3000/'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 2s
    environment:
      NEXT_PUBLIC_SITE_NAME: ${NEXT_PUBLIC_SITE_NAME:-elife}
      API_SERVER: http://api:3000
    ports:
    - 3001:3000

  # expose API and client via proxy
  api:
    image: nginx:latest
    volumes:
    - ./.docker/nginx-browser-test.conf:/etc/nginx/conf.d/default.conf
    - ./test-utils/data/:/www/test-data/

  wiremock:
    image: wiremock/wiremock:3.5.2-1
    ports:
      - 3000:3000
    healthcheck:
      test: curl http://wiremock:3000/__admin/health
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    command:
      - --local-response-templating
      - --port
      - "3000"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/files:/home/wiremock/__files
