# overrides that make the app behave like a production build
services:
  app:
    build:
      context: .
      target: prod
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'apk add curl; curl -X POST http://app:3000/'"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
