import { DM_Sans, Poppins } from 'next/font/google';
import { type JSX } from 'react';
import './common.scss';
import './claims-tree-question-page.scss';

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '600'],
  display: 'swap',
  variable: '--font-dm-sans',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['600'],
  display: 'swap',
  variable: '--font-poppins',
});

export const ClaimsTreeQuestionPage = (): JSX.Element => (
  <>
    <main className={`page-wrapper ${dmSans.variable} ${poppins.variable}`}>
      <a href="#" className="close">
        <span className="visuallyhidden">Navigate away from this page.</span><svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 5L19 19M19 5L5 19" stroke="currentColor" strokeWidth="2"></path></svg>
      </a>
      <div className="claims-tree-pages-content">
        <h1>Question 1</h1>
        <div className="card">
          <header>Question 1
            <span aria-hidden="true" className="dot">&nbsp;&#x2022;&nbsp;</span>
            <span className="visuallyhidden">comprises </span>3 claims<span className="visuallyhidden">.</span>
          </header>
          <p><span className="visuallyhidden">The question: </span>What are the neural mechanisms of interpersonal guilt and responsibility during social decisions under risk?</p>
          <p>The paper investigates how responsibility for a partner&#39;s outcomes in risky choices evokes guilt and which brain regions are involved.</p>
          <p>[icon] Generated by AI from the below extract in the article text</p>
          <p>Quoted text in Abstract:</p>
          <p>“The neural mechanisms underlying guilt evoked during such situations of social responsibility are still unknown.”</p>
        </div>
      </div>
    </main>

  </>
);
