name: Preview

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]

jobs:
  build-preview-image:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'preview') }}
    env:
      IMAGE_REPO: ghcr.io/elifesciences/enhanced-preprints-client
    steps:
      - name: "Create deployment"
        id: deployment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "{\"ref\": \"${{ github.head_ref }}\", \"description\": \"Preview environment\", \"required_contexts\": [\"build-preview-image\"], \"environment\": \"preview-${{ github.event.number }}\", \"state\": \"pending\"}" |
            gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/elifesciences/enhanced-preprints-client/deployments \
            --input -
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and load preview image
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: prod
          load: true
          tags: |
            ${{ env.IMAGE_REPO }}:preview-${{ github.sha }}
      - name: run test
        run: docker run ${{ env.IMAGE_REPO }}:preview-${{ github.sha }} yarn test --ci --watchAll=false
      - name: run lint
        run: docker run ${{ env.IMAGE_REPO }}:preview-${{ github.sha }} yarn lint
      - name: run lint-sass
        run: docker run ${{ env.IMAGE_REPO }}:preview-${{ github.sha }} yarn lint-sass
      - name: push preview image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: prod
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:preview-${{ github.sha }}
      - name: "Update deployment status: Success"
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          deployment_id=$(echo '${{ steps.deployment }}' | jq -r .id)
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/elifesciences/enhanced-preprints-client/deployments/${deployment_id}/statuses \
            -f description='Preview environment image was build successfully' \
            -f state=success \
            -f environment_url=https://pr-${{ github.event.number }}--epp.elifesciences.org/
      - name: "Update deployment status: Failed"
        if: ${{ !success() }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          deployment_id=$(echo '${{ steps.deployment }}' | jq -r .id)
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/elifesciences/enhanced-preprints-client/deployments/${deployment_id}/statuses \
            -f description='Preview environment image build failed' \
            -f state=failure \
