name: Preview

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]

jobs:
  build-preview-image:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'preview') }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push client preview image
        run: IMAGE_REPO_PREFIX=ghcr.io/elifesciences/enhanced-preprints- make build-preview-and-push
