name: Preview

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]

jobs:
  build-preview-image:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'preview') }}
    env:
      IMAGE_REPO: ghcr.io/elifesciences/enhanced-preprints-client
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get PR pull_number
        env:
          GH_TOKEN: ${{ github.token }}
        run: echo "PR_ID=$(pull_number=$(jq --raw-output .pull_request.number \"$GITHUB_EVENT_PATH\"))" >> $GITHUB_ENV
      - name: "Update deployment status: in progress"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/elifesciences/enhanced-preprints-client/deployments \
            -f ref='${{ github.sha }}' \
            -f description='Preview environment'
            -f environment=preview-$PR_ID
            -f state=in_progress
      - name: Build and load preview image
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: prod
          load: true
          tags: |
            ${{ env.IMAGE_REPO }}:preview-${{ github.sha }}
      - name: run test
        run: docker run ${{ env.IMAGE_REPO }}:preview-${{ github.sha }} yarn test --ci --watchAll=false
      - name: run lint
        run: docker run ${{ env.IMAGE_REPO }}:preview-${{ github.sha }} yarn lint
      - name: run lint-sass
        run: docker run ${{ env.IMAGE_REPO }}:preview-${{ github.sha }} yarn lint-sass
      - name: push preview image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: prod
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:preview-${{ github.sha }}
      - name: "Update deployment status: success"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/elifesciences/enhanced-preprints-client/deployments \
            -f ref='${{ github.sha }}' \
            -f description='Preview environment'
            -f environment=preview-$PR_ID
            -f state=success
            -f environment_url=https://pr-${pull_number}--epp.elifesciences.org/
