name: preview-notifications
on:
  repository_dispatch:
    types: [Kustomization/epp-previews]

jobs:
  notification-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Notify
      run: echo "this is a notification too"
