name: Coko Pull Request approval

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, reopened]


jobs:
  check-for-label:
    runs-on: ubuntu-latest
    steps:
      - name: "DEBUG: pull_request object"
        run: echo ${{ toJSON(github.event.pull_request) }}
      - name: auto approve Publish Workflows
        # if: ${{ !startsWith(github.event.pull_request.title, 'Publish manuscript') }}
        run: gh pr edit ${{ github.event.pull_request.number }}--add-label coko-approved
      - name: fail if the label is not present
        run: |
          exit ${{ contains(github.event.pull_request.labels.*.name, 'coko-approved') && '0' || '1' }}
