name: Test notification on sub workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  test:
    name: Linting and unit tests
    runs-on: ubuntu-latest
    steps:
    - run: echo fast tests
  test-integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
    - run: slower tests
    - run: sleep 10
  build-and-push:
    name: Docker image build
    needs: [test, test-integration]
    runs-on: ubuntu-latest
    steps:
    - run: echo build image
    - run: sleep 15

  test-notify:
    needs: [test]
    uses: ./.github/workflows/notify-slack.yaml
    with:
      run_id: ${{ github.run_id }}

  test-integration-notify:
    needs: [test-integration]
    uses: ./.github/workflows/notify-slack.yaml
    with:
      run_id: ${{ github.run_id }}

  build-and-push-notify:
    needs: [build-and-push]
    uses: ./.github/workflows/notify-slack.yaml
    with:
      run_id: ${{ github.run_id }}
