name: Test notification on sub workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: sleep 10
  test-integration:
    runs-on: ubuntu-latest
    steps:
    - run: sleep 15
  build-and-push:
    needs: [test, test-integration]
    runs-on: ubuntu-latest
    steps:
    - run: sleep 20

  test-notify:
    needs: [test]
    uses: ./.github/workflows/notify-slack.yaml
    with:
      run_id: ${{ vars.GITHUB_RUN_ID }}
    secrets: inherit

  test-integration-notify:
    needs: [test-integration]
    uses: ./.github/workflows/notify-slack.yaml
    with:
      run_id: ${{ vars.GITHUB_RUN_ID }}
    secrets: inherit

  build-and-push-notify:
    needs: [build-and-push]
    uses: ./.github/workflows/notify-slack.yaml
    with:
      run_id: ${{ vars.GITHUB_RUN_ID }}
    secrets: inherit
